# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise32"
  config.vm.provision :shell, :path => "aptget.sh", :privileged => false
  config.vm.provision :shell, :path => "virtualenv.sh", :privileged => false
  config.vm.provision :shell, :path => "chemtools.sh", :privileged => false
  config.vm.provision :shell, :path => "deploy.sh", :privileged => false

  config.vm.network :forwarded_port, host: 4567, guest: 80
end
