# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

$setup_script = <<SCRIPT
#!/usr/bin/env bash

echo
echo "----------------------------------"
echo "----------------------------------"

if [ $1 ];
    then
    echo "Running dev install"
    cp -r /tmp/chemtools-webapp .
    cd chemtools-webapp
    rm -rf env/
else
    sudo apt-get install -y git
    if [ ! -d chemtools-webapp ];
        then
        echo "Running staging install"
        git clone https://github.com/crcollins/chemtools-webapp
        cd chemtools-webapp
    else
        echo "Running staging update"
        cd chemtools-webapp
        git pull
    fi
fi

source install.sh
SCRIPT

path = File.join("..", "project", "media", "tests")
id_rsa_ssh_key_pub = File.read(File.join(path, "id_rsa.pub"))

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  if File.file?("chemtools-precise32.box")
    config.vm.box = "chemtools-precise32.box"
  elsif ENV["NEW"]
    config.vm.box = "ubuntu/xenial64"
  else
    config.vm.box = "hashicorp/precise32"
  end
  config.vm.synced_folder "../", "/tmp/chemtools-webapp"


  config.vm.provision :shell, :inline => "echo 'Copying public Key to VM auth_keys...' && mkdir -p /home/vagrant/.ssh && echo '#{id_rsa_ssh_key_pub }' >> /home/vagrant/.ssh/authorized_keys && chmod 600 /home/vagrant/.ssh/authorized_keys"

  config.vm.provision :shell, :inline => $setup_script, :privileged => false, :args => ENV["DEV"]

  config.vm.network :forwarded_port, host: 4567, guest: 80
  config.vm.network :forwarded_port, host: 4568, guest: 443
end
